name: samoo_tutorials
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy<2
  - pandas
  - matplotlib
  - jupyter
  - ipykernel
  - pyemu
  - pip
  - pip:
    - lagpy==2.1.6

